CREATE TABLE Asiakkaat (id INTEGER PRIMARY KEY, nimi TEXT UNIQUE);
CREATE TABLE Paikat (id INTEGER PRIMARY KEY, nimi TEXT UNIQUE)
CREATE TABLE Paketit (id INTEGER PRIMARY KEY, asiakas_id INTEGER, koodi TEXT UNIQUE);
CREATE TABLE Tapahtumat (id INTEGER PRIMARY KEY, paikka_id INTEGER NOT NULL, koodi TEXT NOT NULL, datetime DATETIME NOT NULL, kuvaus TEXT NOT NULL);

